name: Preview Terraform Plan

on:
  pull_request:

jobs:
  preview:
    name: Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout base branch
      uses: actions/checkout@v4
      with:
        ref: '${{ github.event.pull_request.base.ref }}'

    - name: Install tools using asdf
      uses: asdf-vm/actions/install@v2.2.0

    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      run: |
        terramate run infracost breakdown \
          --path=./ \
          --format=json \
          --out-file=infracost-base.json
        terramate run cat infracost-base.json
        
    - name: Checkout PR branch
      uses: actions/checkout@v4
        
    # - name: Create Terraform plan on changed stacks
    #   run: |
    #     terramate run terraform init
    #     terramate run terraform validate
    #     terramate run terraform plan -out ./out.tfplan

    - name: Generate Infracost diff
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run ls -latr
        TM_DISABLE_SAFEGUARDS=git terramate run cat infracost-base.json
        TM_DISABLE_SAFEGUARDS=git terramate run infracost diff \
          --path=./ \
          --format=json \
          --compare-to=infracost-base.json \
          --out-file=infracost.json
    
    - name: Post Infracost comment
      run: |
        tTM_DISABLE_SAFEGUARDS=git erramate run infracost comment github \
          --path=./infracost.json \
          --repo=$GITHUB_REPOSITORY \
          --github-token=${{github.token}} \
          --pull-request=${{github.event.pull_request.number}} \
          --behavior=new