name: Preview Terraform Plan

on:
  # push:
  #   branches: [ "main" ]
  pull_request:

jobs:
  preview:
    name: Plan
    runs-on: ubuntu-latest

    env: 
      working-directory: $pwd

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install tools using asdf
      uses: asdf-vm/actions/install@v2.2.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Create Terraform plan on changed stacks
      working-directory: ${{ env.working-directory }}
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run -- terraform init
        TM_DISABLE_SAFEGUARDS=git terramate run -- terraform validate
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- terraform plan -out '${terramate.stack.path.absolute}'/tfplan.binary
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- terraform show -json '${terramate.stack.path.absolute}'/tfplan.binary > '${terramate.stack.path.absolute}'/plan.json
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- cat plan.json
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- cat '${terramate.stack.path.absolute}'/plan.json


    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      # See https://github.com/infracost/actions/tree/master/setup for other inputs
      # If you can't use this action, see Docker images in https://infracost.io/cicd
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- infracost breakdown \
          --path $(pwd)'${terramate.stack.path.absolute}'/plan.json \
          --format=json \
          --usage-file infracost-usage-medium.yml \
          --out-file=$(pwd)'${terramate.stack.path.absolute}'/infracost-base.json
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- cat $(pwd)'${terramate.stack.path.absolute}'/infracost-base.json
    
    - name: Post Infracost comment
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run --eval -- infracost comment github \
          --path=$(pwd)'${terramate.stack.path.absolute}'/infracost-base.json \
          --repo=$GITHUB_REPOSITORY \
          --github-token=${{github.token}} \
          --pull-request=${{github.event.pull_request.number}} \
          --behavior=new
