name: Preview Terraform Plan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  preview:
    name: Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tools using asdf
      uses: asdf-vm/actions/install@v2.2.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}
        
    - name: Create Terraform plan on changed stacks
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run terraform init
        TM_DISABLE_SAFEGUARDS=git terramate run terraform validate
        TM_DISABLE_SAFEGUARDS=git terramate run terraform plan -out ./out.tfplan
        TM_DISABLE_SAFEGUARDS=git terramate run ls -latr

    # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run ls -latr
        TM_DISABLE_SAFEGUARDS=git terramate run infracost breakdown \
          --path ./out.tfplan \
          --format=json \
          --usage-file infracost-usage-medium.yml \
          --out-file=./infracost-base.json
    
    - name: Post Infracost comment
      run: |
        TM_DISABLE_SAFEGUARDS=git terramate run infracost comment github \
          --path=./infracost-base.json \
          --repo=$GITHUB_REPOSITORY \
          --github-token=${{github.token}} \
          --pull-request=${{github.event.pull_request.number}} \
          --behavior=new